#!/usr/bin/env bash
if [[ "${ASSEMBLY}" =~ "react" ]]; then
  cucumber=./node_modules/.bin/cucumber-electron
else
  cucumber=./node_modules/.bin/cucumber-js
fi

${cucumber} \
--require features/support/env.js \
--require 'features/**/*.ts' \
$@
